label dx_christmas_start:
    play music lets_hear_winter volume 0.7
    scene black
    n "CS wakes up to a snowy winter morning."
    cs "Yes! It snowed today!"
    n "CS looks at his calendar."
    cs "Woohoo!"
    cs "Christmas is almost here!"
    cs "...And you know what that means!"
    cs "I finally get to throw a huge Christmas party at my house!"
    cs "I'm so pumped, I should call everyone again to make sure they are coming."
    n "CS calls all of his guests who he invited a couple weeks ago."
    cs "Alright, well, the party is going to start in 2 days."
    cs "I have not prepared at all."
    cs "Fuck."
    cs "Okay, well first place I need to start is by checking out my house."
    cs "I have this huge mansion, and I don't even use the rest of my house!"
    cs "Let's go look."
    n "CS walks into his living room."
    cs "Well, okay maybe I should bring in the Christmas supplies first."
    cs "Let's go see what we have."
    n "CS goes into his garage."
    cs "Okay, okay, what should I get first..."
    menu:
        "Christmas tree":
            jump dx_christmas_tree
        "Lights and garland":
            jump dx_christmas_lights
        "Ornaments and decorations":
            jump dx_christmas_decor

# christmas tree
label dx_christmas_tree:
    if decor_first and tree_second and lights_first:
        jump dx_christmas_before_anno
    if lights_first or decor_first:
        $ tree_second = True
        cs "Alright, time to get the Christmas tree!"
        n "CS drags the box out of the garage and brings it into his living room."
        n "CS goes back to the garage."
        if lights_first:
            jump dx_christmas_decor
        if decor_first:
            jump dx_christmas_lights
    $ tree_first = True
    if tree_first:
        cs "I should get the Christmas tree first."
        cs "Who doesn't wanna get this thing out? This is the best part of decorating!"
        cs "I just, need to be, careful..."
        cs "Hnng..."
        n "All of a sudden, the shelf tips and all of the supplies fall onto CS!"
        cs "Shit!"
        # crashing SFX
        cs "Ow..."
        n "CS gets himself out of the mess of lights, garland, and Legos."
        # CS steps on a Lego.
        cs "Fuck!"
        cs "Man, what a mess! "
        cs "This is gonna take forever to clean up!"
    jump dx_christmas_anno


# Decorations/lights
label dx_christmas_lights:
    if decor_first and tree_second and lights_first:
        jump dx_christmas_before_anno
    if tree_second or decor_first:
        cs "Alright, I should probably get the lights and garland next."
        n "CS gets the box inside, and then goes back to the garage to grab the next box."
        if tree_second:
            jump dx_christmas_decor
        if decor_first:
            jump dx_christmas_tree
    $ lights_first = True
    if lights_first:
        cs "I should probably get the lights and garland first, they are in the easiest box for me to grab anyways."
        n "CS gets the box inside, and then goes back to the garage to grab the next box."
    menu:
        "Christmas tree":
            jump dx_christmas_tree
        "Ornaments and decorations":
            jump dx_christmas_decor

label dx_christmas_decor:
    if decor_first and tree_second and lights_first:
        jump dx_christmas_before_anno
    if tree_second or lights_first:
        cs "Alright, I should probably get the decorations next."
        n "CS gets the box inside, and then goes back to the garage to grab the next box."
        if tree_second:
            jump dx_christmas_lights
        if lights_first:
            jump dx_christmas_tree
    $ decor_first = True
    if decor_first:
        cs "I'm gonna get the decorations first, I have a huge assortment of Legos in there!"
        n "CS gets the box inside, and then goes back to the garage to grab the next box."   
    menu:
        "Christmas tree":
            jump dx_christmas_tree
        "Lights and garland":
            jump dx_christmas_lights

label dx_christmas_before_anno:
    cs "Well that's all done!"
    cs "I have moved all of the Christmas supplies into the house!"
    cs "This is where the fun part begins!"
    jump dx_christmas_anno

label dx_christmas_anno:
    cs "Maybe I should call someone over to help."
    cs "Lemme see if Anno is around..."
    n "CS decides to call Anno."
    anno "Hello?"
    cs "Hey Anno, CS here!"
    anno "Yes, I know the party is in two days, you just called me."
    cs "Well, I was wondering..."
    cs "If you wanted to help me decorate my house!"
    anno "I still have to get a gift for the gift exchange..."
    anno "...But I can do that tomorrow."
    anno "I'll come over. Be there soon."
    cs "Cool!"
    cs "Alright, I got Anno to come over and help out!"
    cs "I guess I'll just plan out how I want the house to look."
    cs "Actually, shit, it snowed last night!"
    cs "I need to shovel before Anno gets here!"
    n "CS gets dressed and goes out into the garage to get his shovel."
    if tree_first:
        cs "Shit! I hate Legos, but only when they're in my feet!"
    cs "Okay, now the real question is, how much did it snow?"
    n "CS presses the garage button, and nothing happens."
    cs "Damnit, I think it's iced shut."
    cs "I'm gonna have to go out in front."
    n "When CS gets outside, he finds a massive snow drift blocking his garage."
    cs "Well that's just great."
    cs "This is gonna take an hour at least to scoop up."
    cs "I better get to it, I guess."
    n "As CS is about 10 minutes into shoveling, CS hears someone walking up his driveway."
    carguy "Nice snow!"
    carguy "Nooot so nice driveway."
    cs "Look man, I'm trying. It's cold as balls out here."
    carguy "Speaking of balls, you need some help?"
    carguy "I got something you might need!"
    carguy "Crotch Doctor's \"Scratch My Balls\" technology doesn't just help removing shit from your car, it also instantly melts snow!"
    carguy "Watch!"
    n "Carguy unscrews the bottle of Crotch Doctor, and tips it upside down."
    n "A single drop falls into the snow, leaving one small hole."
    cs "Umm..."
    carguy "Hold on, it's just..."
    n "Carguy vigorously shakes the empty bottle."
    carguy "{i}I thought I had more of this...{/i}" 
    carguy "Welp, sorry! Looks like I ran out!"
    n "Carguy turns and trots away though the snow as fast as he can go."
    cs "Well that was a huge waste of time!"
    cs "I really need to finish shoveling my driveway, my face is starting to freeze!"
    n "As CS finishes scooping up the driveway, Anno's car pulls up on his street."
    cs "Just in time!"
    n "CS greets Anno as he pulls up on his driveway."
    anno "Hey, how's it going?"
    cs "Cold. Very cold."
    cs "Let's get inside please it's freezing."
    n "CS and Anno huddle inside and take their jackets off, while they make their way into the living room."
    n "They sit on the couch and catch up with each other while they get warmed up."
    anno "Well CS, how have you been doing?"
    cs "Good! I've enjoyed not being chased by the cops again and just living a roughly normal life."
    anno "Yeah, how was your trip back home after all that? We haven't really talked much since then."
    cs "Well, I had a blast working for LTT for a few days, but eventually I had to escape again because the cops came after us."
    cs "I eventually proved to the cops that I wasn't guilty, and then Billy Mays took us home."
    anno "How the hell did you manage to come across Billy Mays?"
    cs "Crazy coincidence I guess, but it was fun though! I won a golden pencil sharpener!"
    anno "The cops never came after me, so I tried to start up a band, but it didn't really work out."
    #Christmas tree first
    if tree_first:
        anno "By the way, where are all of the decorations?"
        cs "Ah yes, it's all in the garage. I'll show you."
        n "Anno follows CS to his garage."
        n "As they enter the garage, Anno gawks at the mess on the floor."
        anno "Damn bitch, you live like this?"
        cs "...I may have had small mishap when I was trying to get the tree out."
        anno "Small?!"
        cs "Do you think you can help me?"
        cs "I figured it'd be faster if I had a helping hand."
        n "Anno groans."
        anno "I was hoping to be setting up decorations, not cleaning them up."
        anno "...But I guess I don't really have any other option, do I?"
        cs "Here, I'll grab these boxes, and we'll start throwing stuff in them."
        n "After about an hour, they manage to clean up the mess, without stepping on too many Legos."
        n "CS and Anno drag the boxes inside."
    #Setting up decorations
    cs "Well Anno, are you ready to start decorating this place?"
    anno "Yeah! Where do you wanna start?"
    #Living room
    #Kitchen
    #Hallway
    #Entrance
    #Outside
    #After
    cs "Thanks Anno! You really rizzed up my crib!"

    #Day 2
    n "After a good night's sleep, CS slowly wakes up to read the time."
    cs "Huh?"
    cs "Oh shit! It's 2pm already?"
    cs "I should go get all my shopping done!"
    n "CS jolts out of bed and gets ready for the day."
    cs "Thankfully it didn't snow anymore, otherwise my car would have been snowed in!"
    n "CS gets in his car and figures out where to go."
    cs "I went to Walmart last time because they had a deal, but I never shop there regularly."
    cs "To Target we go!"
    n "CS starts up his car and heads to Target."
    cs "Now this is a real store!"
    cs "Everything is mostly clean and neat, no depressing lighting and messy aisles..."
    cs "I should probably stop praising the store and actually buy the groceries I need."
    #Shopping
    n "CS heads over to the grocery aisles."
    cs "Well I need to get some Genergy, of course."
    #Checkout
    n "CS heads over to the checkout lanes."
    cs "Wait, what?"
    cs "There are no lanes open! How the hell am I supposed to check out?"
    cs "Oh wait, I guess self-checkout is open..."
    n "CS gets in the long line wrapped around the self-check area."
    cs "Man, this place is really short staffed, especially for the holidays!"
    customer "They're always like this. I come every day, and they definitely have been losing employees."
    cs "Yikes, I wonder why..."
    cs "Finally, I can checkout."
    n "As CS is checking out, the machine beeps at him."
    cs "What? I scanned this twice? No I didn't!"
    tgt_worker "Oh yeah, it always does that, keep going."
    cs "Okay."
    cs "Ah crap, I scanned this one too many times."
    n "The worker comes back."
    tgt_worker "Hello, what's wrong?"
    cs "Sorry, I scanned this pie 7 times."
    tgt_worker "...how many do you have?"
    cs "I have 2."
    tgt_worker "Wh-- okay hold on."
    tgt_worker "There you go."
    cs "Thanks!"
    cs "Hey wait a minute!"
    n "The target employee runs back over."
    cs "These are ringing up 11.99 per pie!"
    cs "They said they were like 20% off on the sign over there!"
    tgt_worker "Hmm..."
    n "The employee scans the pie."
    tgt_worker "Do you perchance have Target Circle?"
    cs "No?"
    tgt_worker "You need Target Circle to get this deal. Sorry."
    cs "Really?"
    tgt_worker "I'm sorry, but that's just how the deal works."
    cs "Fine, whatever, I'll just keep them."
    n "When CS goes to scan his alcohol, it beeps again and tells him to get out his ID."
    cs "Seriously?!"
    n "The employee runs over again."
    tgt_worker "Oh yeah. I should probably do that for you."
    n "The employee signs into the machine and opens the prompt to enter an ID."
    n "They then wait patiently for CS."
    cs "What? Do you need something from me?"
    tgt_worker "Yeah, I need to check your ID."
    cs "Are you kidding me?"
    tgt_worker "Yes, they will kill me if you don't do it."
    n "CS sighs."
    cs "Here you go."
    n "The target employee punches in his birthday and leaves."
    cs "Kids these days, asking me for my ID..."
    cs "They should hire some new people!"
    cs "Anyways, I need to get home now and put everything away."
    cs "It's the big day tomorrow, and it's gonna be the best party ever!"
label dx_christmas_aftershop:
    n "When CS gets home, he starts putting the groceries away."
    n "As he's finishing up, a D20 he had sitting on the counter gets knocked onto the floor."
    cs "What the hell? When did I ever have one of these?"
    n "CS picks up the die."
    cs "Hey, I got a [d20]!"
label dx_christmas_party_before:
    cs "Today is the day!"
    cs "Now I just have to wait for people to arrive!"
    cs "I wonder who will arrive first?"
    if d20 == 1:
        n "CS waits paiently."
        n "He keeps on waiting."
        cs "Alright, any minute now..."
        cs "The party starts here in about 15 minutes, so people should start showing up soon..."
        n "CS keeps on waiting, but it looks like no one shows up early."
        jump dx_christmas_intro      
    if d20 == 2:
        n "As CS asks himself this, a small car pulls up in the driveway."
        cs "Hmm, let go see who that is!"
        arceus "Hey CS!"
        cs "Hey Arc! Hey Kitty!"
        kitty "What's up?"
        cs "Well, Merry Christmas guys! I'm glad you could travel back here for this!"
        arceus "No problem! I mean, after everything we went through, how could I not?"
        cs "Yeah, well, should we get inside? It's pretty cold out."
        kitty "Well, we are rather warm, but yeah."
        kitty "Let's go inside."
        jump dx_christmas_intro      
    if d20 == 3:
        n "CS peers out the window to see Anno's car pull into the driveway."
        cs "Hey look at that! Anno's here first!"
        anno "Hey CS!"
        anno "I showed up kinda early, but I wanted to see everyone's initial reactions of our decor work!"
        cs "Well I'm glad you showed up, come inside! It's cold out."
        jump dx_christmas_intro      
    if d20 == 4:
        n "All of a sudden, CS hears a futuristic sounding vehicle land outside."
        cs "What the hell is that?"
        digi "Hey CS! How've you been?"
        cs "Hey Digi! Didn't know you have a... spaceship?"
        digi "Well sometimes, you can barely call it that."
        digi "Brr... it's cold out. Can we go inside?"
        cs "Yeah, let's get inside."
        jump dx_christmas_intro      
    if d20 == 5:
        n "As soon as he says that, he feels the house start to shake."
        cs "Wh-- What's going on?"
        n "As the house shakes even faster, a loud train whistle bellows out."
        cs "Holy shit, is that a train?"
        cs "That's a fucking train!"
        tate "Hey CS! How've you been doin'?"
        cs "Tate? Hey! I've been great!"
        mean "Hey CS, Merry Christmas!"
        cs "Merry Christmas to you too, Mean. Shall we get inside."
        tate "Yeah!"
        jump dx_christmas_intro
    if d20 == 6:
        n "As soon as he says that, he feels the house start to shake."
        cs "Wh-- What's going on?"
        n "As the house shakes even faster, a loud train whistle bellows out."
        cs "Holy shit, is that a train?"
        cs "That's a fucking train!"
        tate "Hey CS! How've you been doin'?"
        cs "Tate? Hey! I've been great!"
        mean "Hey CS, Merry Christmas!"
        cs "Merry Christmas to you too, Mean. Shall we get inside."
        tate "Yeah!"
        jump dx_christmas_intro    
    if d20 == 7:
        n "CS notices a familiar blue car roll up on the driveway."
        cs "Look at that! Looks like Billy is here first!"
        billy "Hi! It's Billy!"
        billy "Merry Christmas!"
        cs "Merry Christmas to you too, Billy!"
        billy "Times like these make me wish I could still run commercials."
        billy "It's been hard to sell products by word of mouth, especially since I died that one time."
        cs "That sucks man, I hope this party cheers you up."
        billy "Let's get inside. It's freezing out here."
        jump dx_christmas_intro      
    if d20 == 8:
        n "All of a sudden, CS hears helicopter blades outside of his house."
        cs "Woah, what the hell?"
        n "A Blackhawk helicopter is seen landing out in the middle of the street."
        n "The President of the United States steps out."
        obama "Hello, CS! Nice to meet you."
        cs "Obama?! I didn't think you would actually come!"
        obama "Well, I have enjoyed your content, and when you sent an invitation to your Christmas party, I figured I could come visit for a while."
        obama "Besides, running the political circus has become tiring enough, I need a break."
        cs "Fair enough, I guess! Well Mr. President, let's get inside and wait for the other guests."
        obama "Sure thing. It is very cold outside."
        jump dx_christmas_intro      
    if d20 == 9:
        n "Sirens start blaring outside."
        cs "Uh oh! Why are the cops here?"
        n "CS rushes outside."
        copguy "Heya, CS. Did I scare you?"
        cs "Fuck, yeah you did! I didn't think you were gonna be on duty!"
        copguy "Well someone's gotta be security, right?"
        cs "I… guess?"
        cs "Whatever, let's inside, I'm freezing."
        jump dx_christmas_intro      
    if d20 == 10:
        n "CS looks outside to see a bus pull up."
        cs "Hmm, I wonder who took the bus."
        sheriff "God damnit! Stupid damn wheels! Stuck in the snow!"
        cs "Woah, hey! Who are you?"
        sheriff "Who am I? I'm copguy's boss, that's who!"
        sheriff "I asked him to pick me up, but apparently he had to shop or some shit!"
        sheriff "And I had to take the bus!"
        cs "Oh wow okay, uhm, do you need help?"
        sheriff "Yes!! I keep getting stuck in the snow! Take me inside!"
        jump dx_christmas_intro      
    if d20 == 11:
        n "A beam sound can be heard from outside."
        cs "Hey guys! How have you guys been doing?"
        ed "We've been doing well! Our business has been profitable recently!"
        ed "Even Wesley has made a speedy recovery! He wasn't too happy about getting that metal pipe in his back, though."
        cs "Yeah, I'm uhh..."
        cs "I'm really sorry about that. I still feel bad about taking that too far."
        n "Wesley stares at the ground and mutters."
        wesley "Yeah."
        rich "Well, why don't we get inside? It's freezing!"
        cs "Yeah, let's go!"
        jump dx_christmas_intro      
    if d20 == 12:
        n "An old Dodge Charger pulls up on the driveway."
        cs "Nice car! I wonder if that's Carguy..."
        cs "Hey it's... two Pakoos?"
        k17 "CS!!!"
        k22 "Hey CS. Merry Christmas!"
        cs "Hi, so umm..."
        cs "Are you guys both Pakoo?"
        k22 "It's... kind of complicated."
        k22 "Let's go inside, and we can explain."
        jump dx_christmas_intro      
    if d20 == 13:
        n "A teleport-like sound is heard outside."
        cs "What in the world?"
        cs "Oh hey! Aria, right?"
        aria "Yep, that's me!"
        aria "Goodness, am I too early?"
        cs "A little, but that's okay!"
        cs "I was hoping someone would arrive early."
        aria "Well then. Should we head inside? You're probably getting cold, I assume."
        cs "Yeah, it's kinda freezing out."
        jump dx_christmas_intro      
    if d20 == 14:
        n "Someone's car pulls into the driveway."
        cs "I wonder who that could be?"
        cs "Oh hey, it's Michael!"
        cs "You're still visiting the United States? I thought you were only here for the summer!"
        michael "I decided to spend a whole year over here."
        michael "It's pretty cold out, ain't it?"
        cs "Yeah, let's get inside now."
        jump dx_christmas_intro      
    if d20 == 15:
        n "CS sees Linus' car pulling up outside."
        cs "It looks like Linus got here first!"
        linus "Hey CS! Long time no see!"
        cs "You too, and Luke as well?"
        luke "Hey man! I know we didn't talk much during your short employment, but it was fun having you around!"
        luke "Linus talks a lot about you."
        cs "Oh really?"
        linus "I just think you're a funny guy!"
        linus "What wasn't funny was the cops showing up at LTT, but we can let bygones be bygones."
        cs "Yeah, sorry about all that. It's a long story."
        cs "Why don't we go inside, and i'll explain the whole thing while we wait."
        jump dx_christmas_intro      
    if d20 == 16:
        n "Another Honda Civic shows up in CS' driveway."
        cs "Oh look at that! It's Blank!"
        blank "Hey CS, how have you been?"
        cs "I've been doing well, did you drive safe here?"
        blank "I did, but lots of people on the interstate didn't!"
        blank "I got quite a bit of dashcam footage to watch if you want."
        cs "Sure thing! Let's get inside and watch while we wait for the others."
        jump dx_christmas_intro      
    if d20 == 17:
        n "An unknown car shows up in the driveway."
        cs "I wonder who that is?"
        nova "Hey CS! Thanks for inviting me to your Christmas party!"
        cs "Yeah sure thing!"
        cs "It's been a while, how've you been?"
        nova "Oh y'know, I've been moving a lot, had my friend move in with me..."
        cs "Well, if you wanna chat about it, let's go inside first. It's cold out here."
        jump dx_christmas_intro      
    if d20 == 18:
        n "CS sees a Cherokee pull up to his house."
        cs "What the fuck? Is the military here?"
        cs "Hey, uhh..."
        eliza "Is this the right place?"
        cs "I think so?"
        cs "Are you..."
        eliza "I'm Elizabeth. Behind me is Anne and Grace."
        cs "You might have the wrong place. Sorry."
        eliza "Do you know a Mika? A Mikapara?"
        cs "Is that you?"
        eliza "Close enough."
        cs "Well, should we go inside."
        eliza "Yeah, I guess so."
        jump dx_christmas_intro      
    if d20 == 19:
        n "An orange mini coooper shows up infront of CS' house."
        cs "Holy crap, is that who I think it is?"
        cs "DB! Your the first one here!"
        db "I am??"
        cs "Yes! You managed to be the earliest this time!"
        db "Wow, I can't believe it!"
        cs "Yeah! Let's get inside and we can talk!"
        jump dx_christmas_intro      
    if d20 == 20:
        n "A man in a white shirt walks up to CS' house."
        cs "Who the hell is that?"
        cs "Hey, are you..."
        avgn "I'm the fuckin' Nerd!"
        cs "The Angry Video Game Nerd? I didn't invite you, at least I don't think I did?"
        avgn "It doesn't fucking matter! Merry fucking Christmas!"
        cs "Okay, do you, wanna go inside?"
        avgn "Hell yeah."
        cs "Alright then..."
        jump dx_christmas_intro      
    else:
        n "CS waits paiently."
        n "He keeps on waiting."
        cs "Alright, any minute now..."
        cs "The party starts here in about 15 minutes, so people should start showing up soon..."
        n "CS keeps on waiting, but it looks like no one shows up early." 
        jump dx_christmas_intro      
    #Introductions
label dx_christmas_intro:
    n "By the time of the party, everyone shows up at CS' house in droves."
    cs "Well, it looks like everyone is here, right?"
    anno "DB isn't here yet, but other than that, yeah."
    tate "There are... a lot of people here..."
    digi "Yeah, I wonder where Arc and Kitty are..."
    k17 "OMG hey guys!"
    k17 "You guys all look so… different!"
    k22 "Hi, I'm his--"
    k17 "CS, look how much you've grown!"
    cs "Okay, why are there 2 Pakoos?"
    cs "...and you don't have green hair anymore again?"
    k22 "Oh boy, alright K-17, calm down for one second. I think everyone here needs an explanation."
    cs "Yes please. I didn't want to say it, but it seems like everytime I meet you guys, your appearance always changes!"
    aria "Sorry."
    digi "Did I change too much?"
    cs "No no, just, let Pakoo #2 speak."
    k22 "I'm gonna assume that's me."
    k22 "Alright, so, I'm K-22, the physical manifestation of Pakoo's memories from the year 2022."
    k22 "This is K-17, I'm sure you can figure out what year he is."
    k17 "Remember me? I'm the Sunny D guy!"
    n "CS groans."
    cs "Okay, so what about the green haired one?"
    k22 "That's Addy, our boss. They run this archiving facility far away from here, and I guess they would be the closest version of Pakoo you know, but they aren't here right now."
    k22 "They are running their own Christmas party, which I wanted to be a part of, but this creature right here just HAD to go this party,"
    k22 "and I have to make sure he doesn't get too crazy."
    cs "Great."
    cs "Is that it?"
    k22 "I mean, I could go on, but I'd be here all night."
    mean "Hey, what's going on here?"
    mean "Wait, there's 2 Pakoos now?"
    k22 "Okay, so--"
    tate "I'll just tell him later."
    cs "Alright, well, I'll let you guys talk, I'm gonna check on the others."
    k17 "So, who are you? Are you DigBick?"
    mean "What did you just call me?"
    cs "Hey guys, how are y'all doing?"
    obama "Hello CS, we are all preparing our meals for dinner tonight."
    obama "I'm gonna make a carrot cake."
    billy "I'm gonna make some big city sliders!"
    michael "I've been thinking of preparing some mashed potatoes."
    cs "That all sounds great!"
    cs "What about you, Ed?"
    ed "Well, I think when it comes to cooking, it's just as good as my foundation repair skills."
    ed "I'm preparing a Christmas turkey for our feast."
    cs "Damn! That sounds delicious!"
    cs "Well I hope you are all doing great!"
    cs "I'm gonna go check everyone else!"
    digi "So, this should go here..."
    linus "No, you got the wrong cable!"
    luke "You idiots are both wrong! You are putting in the wrong port!"
    "Digi and Linus" "Ohhhhh..."
    cs "Hey guys! What are you guys doing?"
    digi "Oh, we are just trying to set up a projector to play movies on!"
    linus "Don't ask how this became a 3 man job."
    cs "Well, what about you two?"
    blank "We are working on setting up the music."
    nova "The problem is, I don't really want to have Blank play his shitty music during the party."
    blank "Why? Not all of it's crazy shit, like yours is."
    nova "Shut the hell up!"
    cs "Woah okay, calm down."
    cs "This is a Christmas party, after all. Let's try to have fun."
    cs "I'm gonna go check on anyone else who is here."
    cs "Hey how are you guys? I was looking all over and couldn't find you."
    arceus "Sorry CS, we kind of got overwhelmed."
    kitty "We aren't the best with huge social gatherings."
    cs "Ah, it's okay. I'm just happy to talk."
    arceus "We'll be around when something important happens."
    eliza "Hey, what's up."
    grace "CS! You're that YTP guy!"
    cs "Uhm... who are you three?"
    eliza "Well, do you know Mika at all?"
    cs "I swear to God, are you guys like, memories or some shit as well?"
    eliza "Relax, no, we are just..."
    eliza "Just think of us as them I guess yeah."
    cs "You guys are so complicated."
    arceus "I mean, it wasn't too hard for me to figure out, funny enough."
    n "CS sighs."
    cs "I guess not, I'm just stressed out a bit."
    cs "I just really want this party to go well, and I feel like at this point I don't know half the people here."
    cs "I mean, you split into three people, Pakoo split into two…"
    eliza "I mean, if you want us to, we can step outside for a bit."
    cs "No, no, it's okay."
    cs "I hope you guys have fun, I'm gonna go back to the party."
    #Banter
    n "While the party starts up, copguy and the sheriff get into a predicament."
    sheriff "Hey Copguy!"
    copguy "I know, this party is great, right?"
    sheriff "No, I need to take a shit!"
    copguy "Okay, do you want me to tell everyone?"
    sheriff "Very funny, smartass! I need you to go with me."
    sheriff "My legs don't work, remember?"
    copguy "Damnit, this sucks."
    copguy "Alright, let's go."
    n "Copguy jiggles the bathroom door."
    tate "Occupied!"
    copguy "Sorry sir, we gotta wait."
    sheriff "This is the police! Open up!"
    tate "Awawawawa!!!"
    copguy "Really?"
    sheriff "What? I really have to go!"
    copguy "Whatever, just go. I'll wait here."
    sheriff "What do you mean? You have to wait here with me!"
    sheriff "I can't get off and on the toilet myself!"
    copguy "I think this is the worst crime I've dealt with."
    copguy "Alright, but you better hurry! I don't wanna be in here all day!"
    cs "Is this projector still not set up?"
    digi "No! The projector keeps giving me this really weird error!"
    linus"Not even I've seen this!"
    digi "Watch, I'll turn it on, and…"
    rich "Hey, nice movie!"
    wesley "Looks like you'll have to set that up all over again."
    db "I got here early for this?"
    ed "Hey guys, what movie are we watching?"
    wesley "Nothing until these bozos fix the projector!"
    luke "Okay hold on, I got an idea."
    luke "Everyone step away from the projector."
    n "After a little bit of tech magic, the projector comes to life."
    luke "Tah dah!"
    rich "Finally, we can watch something."
    wesley "Are you 100-percent satisfied, Richard?"
    rich "Only about 80-percent."
    k17 "So, there's a new world trade center now?"
    k22 "What do you mean? They finished that in like 2014!"
    k17 "Oh. Sorry I forgot about that."
    k17 "Okay, so, if big guy over there is DigBick…"
    mean "I'm not DigBick!"
    k17 "Are you DigBick's... girlfriend?"
    tate "What?"
    mean "No, first of all, I'm not fucking DigBick."
    mean "I'm Mean, and this is Tate. We are friends."
    tate "...Yeah."
    k17 "Yeah, you sound mean. What about you?"
    aria "Me? I'm Aria."
    k17 "Who?"
    k22 "Uhh, well..."
    aria "I'm your old friend AWK. I changed."
    k17 "Whaa?"
    k22 "Excuse us for a moment."
    copguy "Please tell me that's it, I can't bear this anymore."
    sheriff "Yep, I'm done!"
    sheriff "Now, are you gonna help me wipe?"
    n "All of a sudden, Copguy's walkie goes off."
    "Walkie" "Officer Copguy, we have a break-in at a house in the neighborhood you are currently at."
    "Walkie" "Can you report on that?"
    copguy "Gladly! Give me a second and I'll be in my car."
    copguy "Sorry boss, as much as I would love to keep helping you, this is important."
    sheriff "Wait! You can't just leave me here!"
    copguy "I'll just be a moment! Don't move."
    sheriff "God damnit! Get back here!!!"
    pause 3.0
    sheriff "\"Don't move.\" Thanks Copguy, you're a real fucking comedian."
    k17 "This is so unfair!"
    k17 "CS said that it's annoying that we changed or whatever, but look at everyone else!"
    k17 "All of my friends have changed so much!"
    k22 "Yeah, well when you are constrained to one year of your life, that can happen."
    k17 "It's just, how do I like, change that?"
    k17 "I can't just change who I am!"
    k22 "Look, you don't need to. I probably should've told you about how people change and whatnot."
    k22 "Honestly, Addy should've told you, but they were probably too busy setting up their party."
    k22 "Speaking of which, do you want to go back home? Celebrate Christmas with Addy?"
    k17 "Hmm..."
    k17 "No, I wanna stay here till the end!"
    k17 "I'll just keep being myself, and try to keep more of an open mind. Thank you K-22!"
    k22 "Damnit, it was worth a try."
    k22 "I wonder how Addy is doing anyways."
    n "K-22 hits up Addy."
    addy "HELLO??"
    k22 "Hey, uhh, how is it going over there?"
    addy "WHAT? I CAN'T HEAR, THE MUSIC IS REALLY LOUD!"
    k22 "I WAS ASKING IF--{w=1.0}{nw}"
    addy "YEAH I'LL CALL YOU LATER, HAVE FUN AT CS' PARTY!"
    k22 "Mother fucker!"
    n "All of a sudden, the wind starts to pick up and snow begins to fall."
    k22 "Brr... I should probably just get back inside and enjoy the party..."
    sheriff "Hey! Is someone there?"
    k17 "Huh?"
    sheriff "Hey you! Can you help me out of here?"
    k17 "Uhh... Uhh..."
    k17 "I'll go get someone!"
    rich "Oh man, I love this part."
    k17 "Hey guys, how do I put this..."
    k17 "The sheriff is stuck in the bathroom?"
    cs "Damnit, one second."
    obama "CS! Are you there?"
    cs "Okay, lemme do this first. The president is calling!"
    #Cooking
    cs "Hey Mr. President, what do you need?"
    obama "You can just call me Obama."
    obama "Second of all, I accidently cut myself while chopping these carrots."
    obama "What a fool I am."
    cs "Oh my god, are you okay?"
    obama "Yes, I'm fine, but I need someone to keep cutting for me."
    obama "Can you do it for me?"
    cs "I guess I can, yeah."
    obama "Great, I just need a few more carrots cut up."
    obama "Give me a moment. I need a Band-Aid."
    cs "Alright, just a few carrots."
    cs "Let's do this."
    #Carrot Karate Chop Minigame
    obama "Well would you look at that!"
    obama "That was some mighty fine chopping, CS!"
    cs "Woohoo!"
    cs "Thank you! Maybe I should cook more."
    cs "Speaking of cooking, I can smell something, burning..."
    obama "It is perhaps the smoke bellowing from the oven?"
    n "All of a sudden, the smoke detectors start beeping!"
    digi "Ahh! Turn it off!"
    nova "Damnit Blank! I said we weren't playing your music!"
    aria "Honestly this is kind of a bop. Keep it going."
    ed "Nooooo!"
    ed "My turkey!"
    n "Ed opens up the oven, only to have even more smoke pour out."
    "CS, Ed, and Obama" "{i}Coughing{/i}"
    n "When the smoke finally clears, Ed pulls out a blackened turkey."
    ed "Damnit! My roast is ruined!"
    billy "Not to fear, Ed! I made my famous restaurant mini-burgers!"
    ed "You mean, steamed hams?"
    billy "Who the actual fuck calls burgers, steamed hams?"
    ed "It's a regional dialect?"
    billy "..."
    billy "Steamed hams... for God's sake..."
    billy "You Texans are crazy."
    michael "I also have my mashed potatoes!"
    cs "Well, at least we still have somewhat of a Christmas dinner."
    n "Ed sheepishly walks back into the living room after throwing away the turkey."
    cs "Obama, finish baking your cake, and we can start eating."
    cs "I'm gonna go check up on everyone while you do that."
    sheriff "...and I had to take that job that left me the way I am."
    sheriff "I could've went to college, studied the paranormal..."
    sheriff "...started up a shower curtain business, run a newspaper business..."
    sheriff "...but no. I had to be a cop."
    grace "Hey, are you almost done in there?"
    sheriff "Just leave me alone..."
    grace "But I really need to go!"
    sheriff "Find another bathoom."
    grace "But this is the only one in the house!"
    sheriff "In this mansion? There is only one damn bathroom?"
    copguy "Hey, sorry, excuse me."
    copguy "Hey boss! You won't believe what I just experienced."
    copguy "This kid caught two burglars trying to rob his house with homemade traps!"
    copguy "It was so impressive, I probably would've fallen for some of them!"
    sheriff "That's great, can you get me off this toilet now?"
    sheriff "I've been thinking of signing my will here because of how long it's been!"
    copguy "Alright, let's get you out of here old man."
    grace "Finally!"
    grace "Guys, the sheriff is out!"
    n "A line starts to form next to the bathroom."
    #Dinner/More Banter
    #Gift Exchange
    cs "Alright everyone! It's time for the gift exchange!"
    cs "Everyone brought a gift, right?"
    n "Everyone nods."
    cs "Alright, well I marked numbers for everyone who showed up, so I'll go around while you guys draw from the bag!"
    n "CS goes around, and everyone draws out of the bag."
    cs "Let's see, who is going first?"
    #roll 1
    cs "Would you look at that! I guess I'm going first!"
    cs "I'm gonna pick, this one!"
    cs "I got..."
    cs "Thigh highs?"
    arceus "Look at that, you got my gift, CS!"
    cs "Well, I guess I have more now!"
    k17 "You wear thigh highs?"
    cs "Yeah, I'm wearing them right now! See?"
    digi "Oh shit, I guess I never looked down to check."
    aria "I just assumed because of the outfit."
    arceus "Welp, it looks like I'm next."
    arceus "I got..."
    arceus "Tea and crumpets?"
    kitty "Arcie! You got my gift!"
    arceus "Sorry! I honestly forgot which one was yours."
    kitty "You saw me carry it in!"
    kitty "Whatever, it's my turn now."
    kitty "Looks like I got..."
    kitty "A… guitar hero controller?"
    cs "Holy shit, that's a Riffmaster!"
    kitty "Is that good?"
    cs "It's just a really good guitar controller."
    anno "That was my gift!"
    anno "It looks like I'm up next."
    anno "I got..."
    anno "What the hell is this?"
    arceus "Ooh! That's a raspberry pi!"
    obama "What are you on about? That doesn't look edible at all!"
    digi "No-- okay it's my gift, so let me explain."
    digi "It's just a small computer that can run python."
    anno "Oh. Cool I guess."
    digi "Well it's my turn now, and I'm gonna steal that Riffmaster!"
    kitty "Damn."
    kitty "Well, what do I do now?"
    cs "You can steal another gift, or pick out another one."
    arceus "Psst! Kitty! Come here!"
    n "Arceus whispers something into their ear."
    kitty "Alright, Anno, hand over your computer thing."
    anno "Welp, next gift I guess."
    anno "I guess I'll pick this one."
    anno "I wonder what it'll be?"
    anno "A Lego set!"
    mean "A TRAIN Lego set!"
    mean "That's my gift, by the way."
    mean "Alright, well I guess it's my turn."
    mean "I'm picking this big one!"
    mean "An instant pot?"
    tate "Mean, you got my gift!"
    mean "Well it's mine now, bitch!"
    mean "Who's next?"
    tate "It's me!"
    tate "Let's see..."
    tate "Billy? Is this yours?"
    billy "It's the Handy Switch!"
    billy "It let's you control any power source, from anywhere!"
    tate "I'm sure I can find a use for this."
    billy "Alright, it's my turn!"
    billy "Wow! Is this the Declaration of Independence?"
    obama "Yep! It's the real deal!"
    obama "Figured I didn't need it no more, so it's yours now!"
    billy "Great! I can probably pitch this!"
    obama "Welp, I guess it's my turn now."
    obama "Metal Gear Solid?"
    copguy "Yeah, that's mine, I didn't know what anyone really wants, so I just found this at the station."
    obama "Dude, this is like my favorite game. I appreciate it."
    copguy "I'm glad."
    copguy "It's my turn now."
    copguy "Okay, so I got \"Gravity Falls Season 2 Director's Cut\"..."
    copguy "...and boss? Is this your gun?"
    sheriff "Yeah, you got my gift. Don't ask how that DVD got in there."
    sheriff "Because I don't know either."
    sheriff "Whatever, it's my turn to pick a gift."
    sheriff "Damn, this is heavy! What the hell is this?"
    sheriff "A bag of cement?"
    ed "We had some leftover from the last house we worked on."
    sheriff "Great, I can drop this on Copguy's head for leaving me in the bathroom!"
    ed "I guess it's my go."
    ed "What the hell? Who brought ice cream? It's all melted!"
    #Audio clip of Richard laughing
    play sound sfx_richlaugh
    pause 3.0
    ed "Damnit Richard! I don't want this!"
    rich "Well let's see what I get."
    rich "Pain pills?"
    wesley "Wait a minute! Those are mine!"
    wesley "I didn't mean to gift that..."
    wesley "I'm gonna steal those since it's my turn now!"
    rich "Hey!"
    rich "What do I even get now?"
    rich "There's nothing else I really want here..."
    rich "I guess it's time to open another present."
    rich "I got Sunny D!"
    n "K17 starts giggling."
    k17 "Alright! My go!"
    k17 "Addy?"
    k22 "Huh?"
    n "K-22 springs up and steals the gift from K-17, sprinting out of the room."
    k22 "I'm sorry, I'll be right back!"
    k17 "What the hay! Now I gotta get another gift!"
    k17 "I'm gonna take the Gravity Falls Commentary!"
    k17 "...and the gun."
    copguy "Alright, then I'm taking the Declaration of Independence!"
    billy "What the actual fuck?"
    billy "Stop stealing gifts!"
    billy "Alright, I'll just take the next gift."
    billy "Adderall?"
    billy "Nope! I'm done with any kind of drug! Not after last time!"
    aria "Aw, that was my gift!"
    aria "You want me to take it?"
    billy "Yes please!"
    n "Aria steals Billy's gift."
    billy "Awesome! I get to pick another gift!"
    billy "Peach syrup!"
    michael "Noice, you got my gift!"
    michael "It goes well with about everything!"
    billy "I'll keep this one!"
    michael "Alright, what gift to choose..."
    michael "I got a new water bottle!"
    linus "You got my LTT water bottle!"
    linus "lttstore.com."
    linus "Alright, it's my turn."
    linus "Hey Luke! I got your gift!"
    luke "Couldn't you tell it was mine?"
    linus "No, how was I supposed to figure that out?"
    luke "Whatever, it's my go now."
    luke "I got..."
    luke "A variation of PC components!"
    blank "Yeah, it's 2 monitors, a 1tb hard drive, and some other things."
    blank "I found it on the curb."
    luke "On the {i}curb{/i}?"
    blank "Yeah, it was just lying there on the curb."
    luke "Damn, well then..."
    blank "It looks like it's my turn next."
    blank "Gamer supps?"
    blank "Guacamole Gamer... Fart... 9000?"
    nova "Dammit you got my gift Blank!"
    blank "Great."
    nova "As much as I want to steal that Adderall, I'm gonna pick a gift."
    nova "Oh boy! I wonder what it is!"
    nova "What the fuck is? Some World War II radio?"
    eliza "Yep. Used by the Soviets in the last half of World War II."
    nova "I'm sure Tristan will like this, I'll probably give it to him."
    eliza "So, it's my turn, let's see what we have..."
    eliza "Dog food."
    eliza "Dog food?"
    db "Ah yeah, I had a lot extra lying around in my car, so I figured why not?"
    db "Well I guess it's finally my turn."
    db "Wow, I got some old coins!"
    digi "Holy shit, I think those are like, really rare!"
    digi "Lemme look it up."
    grace "You got our coins!"
    anne "We had them lying around on the table at home."
    digi "Yeah, those are super rare. I would hold onto those if I were you."
    billy "Antique coins lying around, Tech lying on the curb..."
    billy "Where the hell do you guys live where you find this kinda shit?"
    anne "Well Anne, you wanna pick out the last gift?"
    grace "Yippee! The last gift!"
    grace "I got a cool new t-shirt!"
    cs "Hey! You finally got my gift!"
    cs "Not all of my Depop shirts sold, so it became my gift."
    cs "Does it even fit you?"
    n "Grace puts on the shirt."
    grace "Yep!"
    cs "Woohoo! All of the gifts have been handed out!"


    #Games/Climax
    n "After all of the gifts have been given out, almost everyone has come to the conclusion that the party should end."
    k22 "Well CS, this was wonderful, but we should get going."
    cs "Wait! You aren't gonna stay for the games?"
    k22 "SHHHDADA--{w=1.0}{nw}"
    k17 "We are doing games? Well that's the best part!"
    k22 "Damnit!"
    cs "So you never wanted to stay, you only came here because of him!"
    nova "Well, I'm also leaving, because this asshole won't let me play any good music!"
    blank "Hah! Says you! You wanted to play your trash this whole party!"
    digi "Hey wait a second! Luke!"
    luke "Wha? Oh shit!"
    digi "You were, streaming movies to the projector from your phone?"
    luke "Look, this looked to complicated to setup anyways, so I wanted to make it feel like your plan worked!"
    digi "But, but..."
    digi "I really thought I could set it up this time..."

    #lights out
    sheriff "Hey uhh..."
    sheriff "I think I have finally become blind."
    linus "I think all of our eyes went out."
    cs "No! This can't be happening!"
    cs "My party is ruined!"
    tate "CS, this wasn't your fault."
    cs "Everyone is fighting, no one is having fun!"
    nova "Well yeah, at least I don't listen to Blank's shitty music anymore."
    tate "Can it!"
    tate "Look, we need to stop the arguing and calm down!"
    billy "I am calm!"
    aria "I am clam."
    cs "Okay, I'm trying to relax… and think..."
    cs "Let me feel my way to the basement, and try to check the breaker."
    cs "I'll be right back."
    k17 "Oof!"
    cs "Sorry!"
    arceus "CS? Is that you?"
    cs "Hey Arc. I'm making my way to the breaker to see if I can turn it on."
    arceus "Great. If you find Kitty, lemme know, I don't know where she went."
    arceus "I think she wanted to get extra food, but it's been 20 minutes since then."
    cs "Alright, I'll let you know."


