label knocked_out:
    n "..."
    n "As CS' vision fades back into view, he can also hear a faint heart monitor beeping."
    n "CS immediately snaps up."
    cs "Wha--"
    cs "What happened? How long have I been out?"
    cs "Thank god I didn't catch some virus from a global pandemic or something."
    cs "I guess that's the last time I try to fight someone."
    n "CS sits there for a minute, trying to recollect his memory."
    cs "So I went to go work at LTT, after I..."
    cs "What did I do before that?"
    n "The news starts playing on the TV in CS' room, explaining how 3 criminals broke out of prison a couple days ago."
    cs "Oh shoot! Yeah I went to prison and met Arceus and Anno! I need to get out of here!"