label gameroute_hl:
    stop music
    music end
    n "After that massive fall, CS finds themselves slowly waking up, after what seemed like hours."
    n "CS bleakly opens their eyes."
    cs "Oh god..."
    n "CS groans as they try to sit up, wheezing in pain."
    cs "Hey, wait a minute..."
    cs "Where the hell am I?"
    n "CS finds himself in what looks like a science experiment gone wrong."
    n "Wires are dangling from broken equipment, sparks are shooting out everywhere and bouncing of the ground, and a cart with a weird crystal attach to it is sending out green bolts of electricity."
    cs "Did I... crash into a secret labratory or something?"
    n "CS looks down at themselves, and realizes that they are wearing a different set of armor that they were used to when travelling the verse."
    cs "Okay, so it's definitely been some time since my ship crashed..."
    cs "...But I have no clue where I could be."
    cs "I guess I better take a look around."
    n "CS walks up to the giant metal door, and tries to figure out how to open it."
    cs "Maybe I could try this broken eye-scanner thing."
    n "CS puts his face right up next to it, only for it to sputter and shoot sparks out."
    cs "Dangit. It was worth a try."
    cs "I guess starving to death might not be the worst way to go out."
    n "All of a sudden, the metal door slams open!"
    cs "Hell yeah! Not starving to death in a metal silo today!"
    n "As CS makes his way outside of the metal casket he was trapped in"