default persistent.unlocked_achievements = set()


define achievements = [
    Achievement("ZUP!", "???", "Start the game.", "zup"),
    Achievement("A Great British Pound", "???", "Enjoy :)", "pound"),
    Achievement("Overcaffeinated", "???", "Give an old man {i}way{/i} too much energy.", "genergy"),
    Achievement("Ohai, Mark", "???", "Did-- did that reference land?", "mark"),
    Achievement("I Don't Like People!", "Avoid responsibility.", "Tell CS not to go to Walmart.", "no_person"),
    Achievement("Dead Meme", "???", "Sparta kick Wesley.", "sparta"),
    Achievement("#1 Rated Pooper", "???", "Use your skills to keep your job.", "poop"),
    Achievement("Instinctual Editor", "Let your instincts take over.", "This isn't actually Premiere.", "premiere"),
    Achievement("Crowd Pleaser", "???", "Appease both your fanbases.", "goodrating"),
    Achievement("Can We Go Back?", "???", "Try to go back to Canada.", "compass"),
    Achievement("Ocean Man", "???", "Go west eight times.", "ocean"),
    Achievement("Pacifist", "???", "Don't fight.", "pacifist"),
    Achievement("No Mercy", "???", "Try to kill Arceus.", "nomercy"),
    Achievement("Blaster Disaster", "???", "Outrun the JoJites.", "joj"),
    Achievement("You've Been Gnomed", "???", "Hoo!", "gnome"),
    Achievement("Analog Horror Protagonist", "???", "Survive the Michigan woods.", "forest"),
    Achievement("Creepy Clown Sightings", "???", "Meet a bunch of clowns.", "clowns"),
    Achievement("Pencil Sharpening Day!", "Woohoo!", "Beat Digi at pencil sharpening.", "pencil"),
    Achievement("Pencilovania", "???", "Get a perfect pencil sharpening score.", "300"),
    Achievement("Bored", "Sit through all the car dialouge.", "Sit through all the car dialouge.", "yawn"),
    Achievement("High Roller", "Win a game of Poker.", "Beat Mr. Green at Poker.", "poker"),
    Achievement("The House Doesn't Always Win", "???", "Complete the Golden Grin Casino job on the Death Sentence difficulty.", "house"),
    Achievement("Broken Masquerade", "???", "Peer behind the fourth wall.", "ekhi", True),
    Achievement("Guitar Hero", "???", "Unlock a new career by playing Guitar Hero?", "gh"),
    Achievement("Hi, My Name Is...", "Fill in the blank.", "Name your first song.", "hi"),
    Achievement("Singer-Songwriter", "???", "Write your first song.", "songwriter"),
    Achievement("Independent Artist", "???", "Release an EP.", "ep"),
    Achievement("You Rock!", "???", "Complete your tour.", "rockstar"),
    Achievement("The Threadripper", "???", "Beat up the AMD Fans.", "amd"),
    Achievement("NVIDIA Flex", "???", "Beat up the NVIDIA Fans.", "nvidia"),
    Achievement("I Thought This Was A Visual Novel", "Discover what we spent 1000 lines of code on.", "Win your first RPG battle.", "rpg"),
    Achievement("A Little Help From My Friends", "???", "Gather a full party.", "friends"),
    Achievement("Hopes and Dreams", "???", "Beat Copguy EX.", "souls"),
    Achievement("Machine Gun", "???", "Defeat Copguy EX as CS.", "gun"),
    Achievement("Master Chef", "???", "Win over Gordan Ramsay.", "masterchef"),
    Achievement("The Man In The Red Shirt", "???", "Get in a Tom Scott video.", "redshirt"),
    Achievement("Bottom Gear", "???", "Beat the Top Gear crew in a race.", "bottomgear"),
    Achievement("I'm Scared Right Now...", "Acknowledge your roots.", "Meet the creator of Nekopara.", "nekopara"),
    Achievement("Dame Da Ne", "???", "Sing karaoke in Japan.", "karaoke"),
    Achievement("Have Some Fucking Pizza!", "???", "Meet Scott and Miku.", "pizza"),
    Achievement("Grand Dad", "Fleenstones?!", "Meet Joel in Sweden.", "granddad"),
    Achievement("HoH SiS's Most Wanted", "???", "Complete CSBI.", "csbi"),
    Achievement("Welcome to CSBIII, Mother Fucker", "???", "Complete CSBII.", "csbii"),
    Achievement("That's All, Folks!", "???", "Complete CSBIII.", "csbiii"),
    Achievement("Boingy Boingy Boingy", "???", "Max out CSBounciness and beat the game.", "max_bounce"),
    Achievement("Artifical Unintelligence", "???", "Get the Chat-GPT ending", "gpt", True),
    Achievement("All Over Again", "???", "Beat CSBIII all over again.", "alloveragain", True),
    Achievement("F.U.N.", "???", "Roll a fun value.", "fun", True),
    Achievement("Archived", "???", "Find Addy's Facility.", "archive", True),
    Achievement("Gotta Catch Them All", "Collect every bio.", "Collect every bio.", "bios"),
    Achievement("The Brown Album", "Collect every song in the jukebox.", "Collect every song in the jukebox.", "juke"),
    Achievement("Fin.", "Collect all the endings.", "Collect all the endings.", "end")
]
