default persistent.unlocked_achievements = set()

define achievements = [
    Achievement("ZUP!", "???", "Start the game.", "zup"),
    Achievement("A Great British Pound", "???", "Enjoy :)", "pound"),
    Achievement("Overcaffinated", "???", "Give an old man {i}way{/i} too much energy.", "genergy"),
    Achievement("Ohai, Mark", "???", "Did-- did that reference land?", "mark"),
    Achievement("I Don't Like People!", "Avoid responsibility.", "Tell CS not to go to Wal-Mart.", "no_person"),
    Achievement("Dead Meme", "???", "Sparta kick Wesley.", "sparta"),
    Achievement("#1 Rated Pooper", "???", "Use your skills to keep your job.", "poop"),
    Achievement("Instinctual Editor", "Let your instincts take over.", "This isn't actually Premiere.", "premiere"),
    Achievement("Crowd Pleaser", "???", "Appease both your fanbases.", "goodrating"),
    Achievement("Can We Go Back?", "???", "Try to go back to Canada.", "compass"),
    Achievement("Ocean Man", "???", "Go west eight times.", "ocean"),
    Achievement("Pacifist", "???", "Don't fight.", "pacifist"),
    Achievement("No Mercy", "???", "Try to kill Arceus.", "nomercy"),
    Achievement("Blaster Disaster", "???", "Outrun the JoJites.", "joj"),
    Achievement("Pencil Sharpening Day!", "Woohoo!", "Beat Digi at pencil sharpening.", "pencil"),
    Achievement("Pencilovania", "???", "Get a perfect pencil sharpening score.", "300"),
    Achievement("Bored", "Sit through all the car dialouge.", "Sit through all the car dialouge.", "yawn"),
    Achievement("High Roller", "???", "Beat Mr. Green at Poker.", "poker"),
    Achievement("The House Doesn't Always Win", "???", "Complete the Golden Grin Casino job on the Death Sentence difficulty.", "house"),
    Achievement("Broken Masquerade", "???", "Peer behind the fourth wall.", "ekhi"),
    Achievement("Guitar Hero", "???", "Unlock a new career by playing Guitar Hero?", "gh"),
    Achievement("Hi, My Name Is...", "???", "Name your first song.", "hi"),
    Achievement("Singer-Songwriter", "???", "Write your first song.", "songwriter"),
    Achievement("HoH SiS's Most Wanted", "???", "Complete CSBI.", "csbi"),
    Achievement("Welcome to CSBIII, Mother Fucker", "???", "Complete CSBII.", "csbii"),
    Achievement("That's All, Folks!", "???", "Complete CSBIII.", "csbiii"),
    Achievement("Boingy Boingy Boingy", "???", "Max out CSBounciness and beat the game.", "max_bounce")
]
